from __future__ import annotations

import argparse
import csv
import hashlib
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "results" / "release"
ARTIFACT_MANIFEST = OUT_DIR / "release_artifact_manifest.tsv"
ASSET_MANIFEST = OUT_DIR / "release_asset_manifest.tsv"
ASSET_SUMMARY = OUT_DIR / "release_asset_summary.tsv"
ASSET_NOTES = OUT_DIR / "release_asset_bundle_notes.md"
DEFAULT_ZIP = OUT_DIR / "rmtguard_release_assets_v0.1.0.zip"
MAX_ASSET_BYTES = 50 * 1024 * 1024
SELF_OUTPUTS = {
    "results/release/release_asset_manifest.tsv",
    "results/release/release_asset_summary.tsv",
    "results/release/release_asset_bundle_notes.md",
    "results/release/rmtguard_release_assets_v0.1.0.zip",
}


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _is_forbidden_asset(path_text: str) -> bool:
    return (
        path_text in SELF_OUTPUTS
        or path_text.startswith("data/raw/")
        or path_text.startswith("data/processed/")
        or path_text.startswith("data/")
        or "_probe/" in path_text
        or "_diagnostic/" in path_text
    )


def select_assets(rows: list[dict[str, str]], max_asset_bytes: int = MAX_ASSET_BYTES) -> list[dict[str, str]]:
    selected: list[dict[str, str]] = []
    for row in rows:
        if row.get("release_destination") != "zenodo_or_github_release_asset":
            continue
        if row.get("required_for_submission_package") != "yes":
            continue
        path_text = row["path"]
        path = ROOT / path_text
        if path_text in SELF_OUTPUTS:
            status = "excluded"
            notes = "Release asset manifest outputs are written alongside the bundle and are not hashed as inputs."
        elif _is_forbidden_asset(path_text):
            status = "excluded"
            notes = "Forbidden release asset path; data and probe outputs must not be bundled."
        elif not path.exists():
            status = "missing"
            notes = "Candidate asset is missing."
        elif path.stat().st_size > max_asset_bytes:
            status = "excluded"
            notes = f"Candidate exceeds max asset size {max_asset_bytes} bytes."
        else:
            status = "selected"
            notes = "Selected for release/Zenodo asset bundle."
        selected.append(
            {
                "path": path_text,
                "artifact_type": row.get("artifact_type", ""),
                "size_bytes": str(path.stat().st_size) if path.exists() else row.get("size_bytes", "0"),
                "sha256": _sha256(path) if status == "selected" else "",
                "asset_status": status,
                "notes": notes,
            }
        )
    return selected


def _write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    tmp.replace(path)


def write_manifest(rows: list[dict[str, str]]) -> None:
    _write_tsv(
        ASSET_MANIFEST,
        rows,
        ["path", "artifact_type", "size_bytes", "sha256", "asset_status", "notes"],
    )
    summary: dict[str, dict[str, int]] = {}
    for row in rows:
        bucket = summary.setdefault(row["asset_status"], {"file_count": 0, "size_bytes": 0})
        bucket["file_count"] += 1
        bucket["size_bytes"] += int(row["size_bytes"] or "0")
    summary_rows = [
        {"asset_status": status, "file_count": str(values["file_count"]), "size_bytes": str(values["size_bytes"])}
        for status, values in sorted(summary.items())
    ]
    _write_tsv(ASSET_SUMMARY, summary_rows, ["asset_status", "file_count", "size_bytes"])


def write_notes(rows: list[dict[str, str]], zip_path: Path = DEFAULT_ZIP, executed: bool = False) -> None:
    selected = [row for row in rows if row["asset_status"] == "selected"]
    excluded = [row for row in rows if row["asset_status"] != "selected"]
    lines = [
        "# Release Asset Bundle Notes",
        "",
        "This file is generated by `python scripts/build_release_asset_bundle.py`.",
        "The default mode only writes manifests and checksums; it does not create or upload a zip archive.",
        "",
        f"- Selected asset files: {len(selected)}",
        f"- Non-selected candidates: {len(excluded)}",
        f"- Zip path: `{_rel(zip_path)}`",
        f"- Zip created in this run: `{str(executed)}`",
        "",
        "## Boundary",
        "",
        "Raw public data, processed matrices, and development probe outputs are excluded from this asset bundle.",
        "They should be downloaded from public accessions, regenerated from scripts, or kept as local method-development history.",
        "",
        "## Selected Files",
        "",
        "```text",
    ]
    lines.extend(row["path"] for row in selected)
    lines.extend(["```", ""])
    if excluded:
        lines.extend(["## Non-selected Candidates", "", "```text"])
        lines.extend(f"{row['asset_status']}\t{row['path']}\t{row['notes']}" for row in excluded)
        lines.extend(["```", ""])
    tmp = ASSET_NOTES.with_suffix(ASSET_NOTES.suffix + ".tmp")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    tmp.replace(ASSET_NOTES)


def create_zip(rows: list[dict[str, str]], zip_path: Path = DEFAULT_ZIP) -> None:
    selected = [row for row in rows if row["asset_status"] == "selected"]
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = zip_path.with_suffix(zip_path.suffix + ".tmp")
    with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for row in selected:
            path = ROOT / row["path"]
            archive.write(path, arcname=row["path"])
        archive.write(ASSET_MANIFEST, arcname=_rel(ASSET_MANIFEST))
        archive.write(ASSET_SUMMARY, arcname=_rel(ASSET_SUMMARY))
        archive.write(ASSET_NOTES, arcname=_rel(ASSET_NOTES))
    tmp.replace(zip_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a checksum manifest, and optionally a zip, for release/Zenodo assets.")
    parser.add_argument("--artifact-manifest", type=Path, default=ARTIFACT_MANIFEST)
    parser.add_argument("--zip", type=Path, default=DEFAULT_ZIP)
    parser.add_argument("--execute", action="store_true", help="Create the zip archive. Default only writes manifests.")
    args = parser.parse_args(argv)

    artifact_rows = _read_tsv(args.artifact_manifest)
    asset_rows = select_assets(artifact_rows)
    write_manifest(asset_rows)
    write_notes(asset_rows, args.zip, executed=False)
    if args.execute:
        create_zip(asset_rows, args.zip)
        write_notes(asset_rows, args.zip, executed=True)
    print(_rel(ASSET_MANIFEST))
    print(_rel(ASSET_SUMMARY))
    print(_rel(ASSET_NOTES))
    print(f"{'zip_created' if args.execute else 'dry_run'}\t{sum(row['asset_status'] == 'selected' for row in asset_rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
