from __future__ import annotations

"""Build the 20-50 JIF publication route for RMTGuard.

This is a decision artifact, not a guarantee of journal acceptance.
"""

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GATE_EVIDENCE = ROOT / "results" / "gates" / "gate_evidence.tsv"
OUT_TSV = ROOT / "results" / "gates" / "publication_20_50_decision.tsv"
OUT_MD = ROOT / "docs" / "publication_20_50_rescue_plan.md"


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def _write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    tmp.replace(path)


def _write_text(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    tmp.replace(path)


def _gate_status(rows: list[dict[str, str]]) -> dict[str, str]:
    return {row.get("gate_id", ""): row.get("status", "pending") for row in rows}


def build_decision_rows(gates: list[dict[str, str]]) -> list[dict[str, str]]:
    statuses = _gate_status(gates)
    blockers = [
        gate_id
        for gate_id, status in statuses.items()
        if statuses.get(gate_id) != "pass"
    ]
    nature_methods_ready = not blockers and all(status == "pass" for status in statuses.values())
    rows = [
        {
            "journal": "Nature Methods",
            "verified_2024_jif": "32.1",
            "verified_2024_5yr_jif": "51.7",
            "source_url": "https://www.nature.com/nmeth/journal-impact",
            "within_20_50_jif": "yes",
            "fit_for_current_project": "primary_target_if_gates_pass",
            "current_readiness": "ready" if nature_methods_ready else "not_ready",
            "blocking_items": ";".join(blockers) if blockers else "none",
            "required_positioning": "Methods Article centered on random-matrix noise control, diagnostic no-call, public benchmarks, and reproducible software.",
        },
        {
            "journal": "Nature Biotechnology",
            "verified_2024_jif": "41.7",
            "verified_2024_5yr_jif": "59.5",
            "source_url": "https://www.nature.com/nbt/journal-impact",
            "within_20_50_jif": "yes",
            "fit_for_current_project": "stretch_only",
            "current_readiness": "not_ready",
            "blocking_items": "needs platform-level biological or biotechnology advance beyond current scRNA-seq workflow benchmark",
            "required_positioning": "Would require a broader platform/toolkit story with major biological adoption, not the current RMTGuard evidence package.",
        },
        {
            "journal": "Genome Biology",
            "verified_2024_jif": "9.4",
            "verified_2024_5yr_jif": "16.3",
            "source_url": "https://genomebiology.biomedcentral.com/about",
            "within_20_50_jif": "no",
            "fit_for_current_project": "realistic_fallback_if_strict_jif_relaxed",
            "current_readiness": "not_ready_until_software_release",
            "blocking_items": "software_release; current 2-year JIF below 20",
            "required_positioning": "Genomics workflow and benchmark resource with transparent limitations.",
        },
    ]
    return rows


def build_markdown(rows: list[dict[str, str]], gates: list[dict[str, str]]) -> list[str]:
    status_by_gate = _gate_status(gates)
    lines = [
        "# 20-50 JIF Publication Rescue Plan",
        "",
        "This file is generated by `python scripts/build_publication_20_50_plan.py`.",
        "",
        "## Non-Negotiable Boundary",
        "",
        "No one can guarantee journal acceptance. The controllable commitment is gate discipline: do not submit a 20-50 JIF manuscript until the evidence package meets the target journal's requirements.",
        "",
        "## Current Decision",
        "",
        "- Strict 20-50 JIF route: `not ready`.",
        f"- `stability_advantage`: `{status_by_gate.get('stability_advantage', 'pending')}`.",
        f"- `diagnostic_no_call_validation`: `{status_by_gate.get('diagnostic_no_call_validation', 'pending')}`.",
        f"- `software_release`: `{status_by_gate.get('software_release', 'pending')}`.",
        "- Current best 20-50 target remains Nature Methods, not Nature Biotechnology.",
        "- Genome Biology is a realistic fallback only if strict 20-50 JIF is relaxed; its verified 2024 JIF is below 20.",
        "",
        "## Journal Route",
        "",
    ]
    for row in rows:
        lines.extend(
            [
                f"### {row['journal']}",
                "",
                f"- Verified 2024 JIF: `{row['verified_2024_jif']}`.",
                f"- Verified 2024 5-year JIF: `{row['verified_2024_5yr_jif']}`.",
                f"- Within 20-50 JIF: `{row['within_20_50_jif']}`.",
                f"- Fit: `{row['fit_for_current_project']}`.",
                f"- Current readiness: `{row['current_readiness']}`.",
                f"- Blocking items: `{row['blocking_items']}`.",
                f"- Required positioning: {row['required_positioning']}",
                f"- Source: {row['source_url']}",
                "",
            ]
        )
    lines.extend(
        [
            "## Execution Gates I Will Enforce",
            "",
            "1. `stability_advantage` is acceptable only under the callability-aware framing; do not claim broad fixed-PC superiority.",
            "2. `software_release` must become pass before any journal submission.",
            "3. Benchmark baselines must include Scanpy-like, fixed PCs, and at least one stronger parameter-selection baseline before final submission.",
            "4. PDAC/TME must remain a public use case unless it produces externally validated biology.",
            "5. No claim can exceed the generated claim-evidence matrix.",
            "",
            "## Source Tables",
            "",
            f"- Gate evidence: `{_rel(GATE_EVIDENCE)}`",
            f"- Publication decision TSV: `{_rel(OUT_TSV)}`",
        ]
    )
    return lines


def main() -> int:
    gates = _read_tsv(GATE_EVIDENCE)
    rows = build_decision_rows(gates)
    _write_tsv(
        OUT_TSV,
        rows,
        [
            "journal",
            "verified_2024_jif",
            "verified_2024_5yr_jif",
            "source_url",
            "within_20_50_jif",
            "fit_for_current_project",
            "current_readiness",
            "blocking_items",
            "required_positioning",
        ],
    )
    _write_text(OUT_MD, build_markdown(rows, gates))
    print(_rel(OUT_TSV))
    print(_rel(OUT_MD))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
