from __future__ import annotations

"""Build an email-ready packet for corresponding-author Figure 4 sign-off.

Author: RMTGuard development team
Date: 2026-05-10
Purpose: Create a draft email, .eml file with the sign-off DOCX attached, and
an idempotent confirmation tracker for the Nature Methods presubmission gate.
Data source: Generated sign-off packet and Nature Methods go/no-go artifacts.
Method notes: This script does not send email. It creates local files only.
"""

import csv
from email.message import EmailMessage
from email.utils import formatdate
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

SIGNOFF_DOCX = ROOT / "output" / "doc" / "RMTGuard_corresponding_author_signoff_packet.docx"
SIGNOFF_MD = ROOT / "manuscript" / "corresponding_author_signoff_packet.md"
GO_NO_GO_MD = ROOT / "docs" / "nature_methods_go_no_go_final.md"
PRESUBMISSION_MD = ROOT / "manuscript" / "nature_methods_presubmission_inquiry.md"

TRACKER_TSV = ROOT / "metadata" / "corresponding_author_signoff_tracker.tsv"
TRACKER_MD = ROOT / "docs" / "corresponding_author_signoff_tracker.md"
EMAIL_MD = ROOT / "manuscript" / "corresponding_author_signoff_email_draft.md"
OUT_EMAIL_DIR = ROOT / "output" / "email"
OUT_EML = OUT_EMAIL_DIR / "RMTGuard_corresponding_author_signoff_email.eml"
OUT_README = OUT_EMAIL_DIR / "README.md"

CONFIRMATION_TEXT = (
    "Figure 4 will be presented only as a bounded public-data PDAC/TME "
    "showcase of RMTGuard callability, not as a new PDAC mechanism, CAF "
    "discovery, prognosis, therapy-response, clinical-validation, or "
    "patient-level claim."
)

AUTHORS = [
    {
        "author_name": "Yi Miao",
        "email": "miaoyi@njmu.edu.cn",
        "role": "corresponding_author_1",
    },
    {
        "author_name": "Han Yan",
        "email": "carrick8862@163.com",
        "role": "corresponding_author_2",
    },
]


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def _write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    tmp.replace(path)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text.rstrip() + "\n", encoding="utf-8")
    tmp.replace(path)


def build_tracker_rows() -> list[dict[str, str]]:
    existing = {row.get("email", ""): row for row in _read_tsv(TRACKER_TSV)}
    rows: list[dict[str, str]] = []
    for author in AUTHORS:
        old = existing.get(author["email"], {})
        rows.append(
            {
                "author_name": author["author_name"],
                "email": author["email"],
                "role": author["role"],
                "required_confirmation": CONFIRMATION_TEXT,
                "status": old.get("status", "pending_author_reply"),
                "confirmed_at": old.get("confirmed_at", ""),
                "evidence_path": old.get("evidence_path", ""),
                "notes": old.get("notes", ""),
            }
        )
    return rows


def build_tracker_markdown(rows: list[dict[str, str]]) -> str:
    all_confirmed = all(row["status"] == "confirmed" for row in rows)
    proxy_assumption = bool(rows) and all(
        row["status"] == "proxy_authorized_working_assumption" for row in rows
    )
    current_status = (
        "all_confirmed"
        if all_confirmed
        else (
            "proxy_authorized_working_assumption"
            if proxy_assumption
            else "pending_author_reply"
        )
    )
    lines = [
        "# Corresponding Author Figure 4 Sign-off Tracker",
        "",
        "Generated by `python scripts/build_corresponding_author_email_packet.py`.",
        "",
        f"- Current status: `{current_status}`.",
        "- Nature Methods full submission remains `NO-GO` regardless of this tracker.",
        "- Nature Methods presubmission inquiry can proceed only after both corresponding authors are marked `confirmed` and final wording is reviewed.",
        "- `proxy_authorized_working_assumption` permits internal drafting only; it does not unlock editor-facing submission.",
        "",
        "## Tracker Table",
        "",
        "| Author | Email | Role | Status | Confirmed at | Evidence | Notes |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| "
            + row["author_name"]
            + " | "
            + row["email"]
            + " | "
            + row["role"]
            + " | `"
            + row["status"]
            + "` | "
            + row["confirmed_at"]
            + " | "
            + row["evidence_path"]
            + " | "
            + row["notes"]
            + " |"
        )
    lines.extend(
        [
            "",
            "## How To Update After Reply",
            "",
            "Edit `metadata/corresponding_author_signoff_tracker.tsv` and set `status` to `confirmed` only when the author's reply explicitly accepts the bounded Figure 4 wording.",
            "",
            "Allowed confirmation text:",
            "",
            "> " + CONFIRMATION_TEXT,
            "",
            "Do not mark confirmed if the reply asks to frame Figure 4 as a PDAC mechanism, CAF discovery, clinical validation, prognosis, therapy-response, or patient-level result.",
        ]
    )
    return "\n".join(lines)


def build_email_body() -> str:
    return f"""Dear Professor Miao and Dr Yan,

We are preparing the RMTGuard Nature Methods presubmission route. Before any
presubmission inquiry is sent, we need corresponding-author confirmation of the
bounded Figure 4 wording.

Current decision:

- Full Nature Methods submission: NO-GO at this stage.
- Nature Methods presubmission inquiry: conditional go after corresponding-author acknowledgement.
- Genome Biology fallback: ready if Nature Methods feedback is not encouraging.
- Acceptance guarantee: impossible.

Please confirm the following wording:

{CONFIRMATION_TEXT}

The attached Word file contains the sign-off packet, exact Figure 4 caption
draft, and stop rules. If you agree, please reply with:

We confirm the bounded Figure 4 wording for RMTGuard.

If you would like to revise Figure 4 wording, please mark the exact sentence
that should be changed. We should not describe Figure 4 as a new PDAC
mechanism, CAF discovery, prognosis, therapy-response, clinical-validation, or
patient-level finding.

Best regards,

Chongfa Chen
"""


def build_email_markdown() -> str:
    return """# Corresponding Author Sign-off Email Draft

Generated by `python scripts/build_corresponding_author_email_packet.py`.

## To

- Yi Miao <miaoyi@njmu.edu.cn>
- Han Yan <carrick8862@163.com>

## Subject

RMTGuard Figure 4 bounded wording sign-off before Nature Methods presubmission

## Attachment

`output/doc/RMTGuard_corresponding_author_signoff_packet.docx`

## Body

```text
""" + build_email_body().rstrip() + """
```

## Source Files

- Sign-off packet: `""" + _rel(SIGNOFF_MD) + """`
- Go/no-go packet: `""" + _rel(GO_NO_GO_MD) + """`
- Presubmission inquiry draft: `""" + _rel(PRESUBMISSION_MD) + """`
- Email draft EML: `""" + _rel(OUT_EML) + """`
"""


def build_eml() -> None:
    OUT_EMAIL_DIR.mkdir(parents=True, exist_ok=True)
    message = EmailMessage()
    message["To"] = ", ".join(
        f"{author['author_name']} <{author['email']}>" for author in AUTHORS
    )
    message["Subject"] = (
        "RMTGuard Figure 4 bounded wording sign-off before Nature Methods presubmission"
    )
    message["Date"] = formatdate(localtime=True)
    message.set_content(build_email_body())

    if SIGNOFF_DOCX.exists():
        payload = SIGNOFF_DOCX.read_bytes()
        message.add_attachment(
            payload,
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=SIGNOFF_DOCX.name,
        )

    tmp = OUT_EML.with_suffix(".eml.tmp")
    tmp.write_bytes(bytes(message))
    tmp.replace(OUT_EML)


def build_readme() -> str:
    return """# RMTGuard Email Draft Outputs

This folder contains local `.eml` drafts. These files are not sent by scripts.

## Files

- `RMTGuard_author_declaration_confirmation_email.eml`: request final author
  confirmation for title-page metadata, CRediT, funding, competing interests,
  public-data ethics, reporting summary, and bounded Figure 4 wording.
- `RMTGuard_corresponding_author_signoff_email.eml`: send this first to request
  Figure 4 bounded-wording acknowledgement from Yi Miao and Han Yan.
- `RMTGuard_nature_methods_presubmission_inquiry_HOLD.eml`: locked Nature
  Methods presubmission draft. Do not send while the send packet reports a
  `hold_*` status.

## Boundary

The corresponding-author sign-off email can be used only to request author
acknowledgement. The Nature Methods HOLD draft intentionally has no recipient
because the official submission/presubmission route must be verified manually
immediately before sending.

## Regenerate

```bash
python scripts/build_author_declaration_email_packet.py
python scripts/build_corresponding_author_email_packet.py
python scripts/build_nature_methods_presubmission_send_packet.py
```
"""


def main() -> int:
    rows = build_tracker_rows()
    _write_tsv(
        TRACKER_TSV,
        rows,
        [
            "author_name",
            "email",
            "role",
            "required_confirmation",
            "status",
            "confirmed_at",
            "evidence_path",
            "notes",
        ],
    )
    _write_text(TRACKER_MD, build_tracker_markdown(rows))
    _write_text(EMAIL_MD, build_email_markdown())
    build_eml()
    _write_text(OUT_README, build_readme())
    print(_rel(TRACKER_TSV))
    print(_rel(TRACKER_MD))
    print(_rel(EMAIL_MD))
    print(_rel(OUT_EML))
    print(_rel(OUT_README))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
