#!/usr/bin/env python
"""Build the rare-state power claim-boundary report.

Author: RMTGuard development team
Date: 2026-05-04
Purpose: Convert 50-repeat rare-state power curves into allowed and prohibited
manuscript claims so weak-regime failures are not hidden.
Data source: results/calibration/realistic_null_summary.tsv and
results/calibration/rare_state_power_summary.tsv.
Method notes: This is claim-control metadata, not a new experiment.
"""

from __future__ import annotations

import csv
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
NULL_SUMMARY = ROOT / "results" / "calibration" / "realistic_null_summary.tsv"
POWER_SUMMARY = ROOT / "results" / "calibration" / "rare_state_power_summary.tsv"
OUT_TSV = ROOT / "results" / "submission" / "rare_state_claim_boundary.tsv"
OUT_MD = ROOT / "docs" / "rare_state_claim_boundary.md"


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _write_tsv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    df.to_csv(tmp, sep="\t", index=False, quoting=csv.QUOTE_MINIMAL)
    tmp.replace(path)


def _write_text(text: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text.rstrip() + "\n", encoding="utf-8")
    tmp.replace(path)


def build_boundary(null_summary: pd.DataFrame, power: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    max_false_call = float(null_summary["false_call_rate"].max())
    for row in power.itertuples(index=False):
        if row.power >= 0.80:
            claim_status = "supported"
            claim_text = (
                "Rare-state recovery is supported for this simulated setting "
                "under the stated prevalence/effect-size assumptions."
            )
        elif row.power >= 0.50:
            claim_status = "borderline_limit"
            claim_text = (
                "Rare-state recovery is partial; report as a transition zone "
                "and do not use it as a main positive claim."
            )
        else:
            claim_status = "unsupported_limit"
            claim_text = (
                "Rare-state recovery is weak; this setting must be reported as "
                "a limitation and cannot support a universal rare-state claim."
            )
        rows.append(
            {
                "prevalence": row.prevalence,
                "effect_size": row.effect_size,
                "n_repeats": int(row.n_repeats),
                "power": row.power,
                "power_ci95_low": row.power_ci95_low,
                "power_ci95_high": row.power_ci95_high,
                "mean_rare_f1": row.mean_rare_f1,
                "mean_rare_f1_ci95_low": row.mean_rare_f1_ci95_low,
                "mean_rare_f1_ci95_high": row.mean_rare_f1_ci95_high,
                "no_call_rate": row.no_call_rate,
                "max_null_false_call_rate": max_false_call,
                "claim_status": claim_status,
                "claim_text": claim_text,
            }
        )
    return pd.DataFrame(rows)


def build_doc(boundary: pd.DataFrame, null_summary: pd.DataFrame) -> str:
    unsupported = boundary[boundary["claim_status"] == "unsupported_limit"]
    borderline = boundary[boundary["claim_status"] == "borderline_limit"]
    supported = boundary[boundary["claim_status"] == "supported"]
    max_false_call = float(null_summary["false_call_rate"].max())
    max_false_signal = float(null_summary["false_signal_rate"].max())
    min_power_row = boundary.sort_values("power", ascending=True).iloc[0]

    lines = [
        "# Rare-State Claim Boundary",
        "",
        "Generated by `python scripts/build_rare_state_claim_boundary.py`.",
        "",
        "## Bottom Line",
        "",
        f"- Realistic-null false call max: `{max_false_call:.3f}`.",
        f"- Realistic-null false signal max: `{max_false_signal:.3f}`.",
        f"- Supported rare-state settings: `{len(supported)}` of `{len(boundary)}`.",
        f"- Borderline rare-state settings: `{len(borderline)}` of `{len(boundary)}`.",
        f"- Unsupported rare-state settings: `{len(unsupported)}` of `{len(boundary)}`.",
        f"- Weakest setting: prevalence `{min_power_row.prevalence:.3f}`, effect size `{min_power_row.effect_size:.2f}`, power `{min_power_row.power:.3f}`.",
        "",
        "## Allowed Claim",
        "",
        "RMTGuard controls false calls in the tested count-preserving null models and recovers rare states with high power in moderate-prevalence or stronger-effect simulated regimes.",
        "",
        "## Required Limitation",
        "",
        "RMTGuard should not be described as universally recovering all rare states. The lowest-prevalence and weakest-effect regimes show limited power and must be reported as an explicit boundary of the method.",
        "",
        "## Prohibited Claim",
        "",
        "Do not claim broad or universal rare-state recovery across all scRNA-seq settings.",
        "",
        "## Boundary Table",
        "",
        "| Prevalence | Effect size | Power | 95% CI | Rare F1 | Status |",
        "| ---: | ---: | ---: | --- | ---: | --- |",
    ]
    for row in boundary.itertuples(index=False):
        lines.append(
            f"| {row.prevalence:.3f} | {row.effect_size:.2f} | {row.power:.3f} | {row.power_ci95_low:.3f}-{row.power_ci95_high:.3f} | {row.mean_rare_f1:.3f} | `{row.claim_status}` |"
        )
    lines.extend(
        [
            "",
            "## Source Artifacts",
            "",
            f"- Null summary: `{_rel(NULL_SUMMARY)}`",
            f"- Power summary: `{_rel(POWER_SUMMARY)}`",
            f"- Claim-boundary TSV: `{_rel(OUT_TSV)}`",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    null_summary = pd.read_csv(NULL_SUMMARY, sep="\t")
    power = pd.read_csv(POWER_SUMMARY, sep="\t")
    boundary = build_boundary(null_summary, power)
    _write_tsv(boundary, OUT_TSV)
    _write_text(build_doc(boundary, null_summary), OUT_MD)
    print(_rel(OUT_TSV))
    print(_rel(OUT_MD))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
