"""Build email and chat drafts for RMTGuard author declarations.

Author: RMTGuard contributors
Date: 2026-05-12
Purpose: Create ready-to-send local drafts requesting author confirmation of
title-page metadata, postal code, CRediT roles, funding, competing interests,
ethics/public-data wording, Figure 4 bounded wording, and reporting-summary
items.
Data source: results/submission/author_declaration_confirmation_checklist.tsv
and output/doc/RMTGuard_author_declaration_confirmation_packet.docx.
Method notes: This script creates local files only. It does not send email and
does not mark any author item as confirmed.
"""

from __future__ import annotations

import csv
from email.message import EmailMessage
from email.utils import formatdate
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

CHECKLIST = ROOT / "results" / "submission" / "author_declaration_confirmation_checklist.tsv"
PACKET_DOCX = ROOT / "output" / "doc" / "RMTGuard_author_declaration_confirmation_packet.docx"
PACKET_MD = ROOT / "docs" / "author_declaration_confirmation_packet.md"
DASHBOARD = ROOT / "docs" / "high_impact_submission_dashboard.md"

OUT_EMAIL_DIR = ROOT / "output" / "email"
OUT_EML = OUT_EMAIL_DIR / "RMTGuard_author_declaration_confirmation_email.eml"
OUT_README = OUT_EMAIL_DIR / "README.md"
OUT_EMAIL_MD = ROOT / "manuscript" / "author_declaration_confirmation_email_draft.md"
OUT_WECHAT_MD = ROOT / "manuscript" / "author_declaration_confirmation_wechat_draft.md"
OUT_INTAKE = ROOT / "docs" / "author_declaration_reply_intake_runbook.md"


AUTHORS = [
    {"name": "Yi Miao", "email": "miaoyi@njmu.edu.cn", "role": "corresponding_author_1"},
    {"name": "Han Yan", "email": "carrick8862@163.com", "role": "corresponding_author_2"},
]


def _rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


def read_tsv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text.rstrip() + "\n", encoding="utf-8")
    tmp.replace(path)


def item_lines(rows: list[dict[str, str]]) -> list[str]:
    lines = []
    for idx, row in enumerate(rows, start=1):
        lines.append(
            f"{idx}. {row.get('item_id', '')}: {row.get('confirmation_question', '')}\n"
            f"   Current value/status: {row.get('current_value', '')} / {row.get('current_status', '')}\n"
            f"   Requested action: {row.get('required_author_action', '')}"
        )
    return lines


def build_email_body(rows: list[dict[str, str]]) -> str:
    items = "\n\n".join(item_lines(rows))
    return f"""Dear Professor Miao and Dr Yan,

We are preparing the RMTGuard high-impact journal package. Before any v0.1.1
release, Zenodo archive update, or editor-facing presubmission inquiry, we need
written confirmation of the author-controlled manuscript declarations listed
below.

Current project decision:

- Full Nature Methods submission: NO-GO at this stage.
- Nature Methods presubmission inquiry: conditional go after author confirmation.
- Current high-impact dashboard: continue development; do not submit.
- Acceptance guarantee: impossible.

Please review the attached Word packet and confirm or revise the following
items:

{items}

If everything is correct, please reply with:

We confirm the RMTGuard author declarations, title-page metadata, CRediT roles,
public-data ethics statement, reporting-summary items, and bounded Figure 4
wording as written.

If any item needs revision, please quote the item number and provide the exact
replacement text. Please do not approve the package if any private clinical
data, unpublished identifiable metadata, unreported funding, or competing
interest should be disclosed.

Best regards,

Chongfa Chen
"""


def build_email_markdown(rows: list[dict[str, str]]) -> str:
    return f"""# Author Declaration Confirmation Email Draft

Generated by `python scripts/build_author_declaration_email_packet.py`.

## To

- Yi Miao <miaoyi@njmu.edu.cn>
- Han Yan <carrick8862@163.com>

## Subject

RMTGuard author declarations and Figure 4 wording confirmation before release/presubmission

## Attachment

`{_rel(PACKET_DOCX)}`

## Body

```text
{build_email_body(rows).rstrip()}
```

## Source Files

- Confirmation packet: `{_rel(PACKET_MD)}`
- High-impact dashboard: `{_rel(DASHBOARD)}`
- Email EML draft: `{_rel(OUT_EML)}`
"""


def build_wechat_text(rows: list[dict[str, str]]) -> str:
    short_items = "\n".join(
        f"{idx}. {row.get('item_id', '')}" for idx, row in enumerate(rows, start=1)
    )
    return f"""# Author Declaration Confirmation WeChat Draft

Generated by `python scripts/build_author_declaration_email_packet.py`.

```text
老师您好，RMTGuard 现在代码/DOI和资料包已经基本整理好，但投稿前还不能提交，原因是作者声明和 Figure 4 边界还需要书面确认。

我已整理好 Word 确认包，需要确认 8 项：
{short_items}

请您帮我确认：如果内容都可以，请回复“确认按当前版本使用”；如果需要修改，请直接指出第几项和替换文字。

特别提醒：Figure 4 只能作为公共数据 PDAC/TME use case，不能写成新的机制、临床验证、预后、治疗反应或患者层面结论。
```

## Attachment

Send this Word file together with the message:

`{_rel(PACKET_DOCX)}`
"""


def build_intake_runbook(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Author Declaration Reply Intake Runbook",
        "",
        "Generated by `python scripts/build_author_declaration_email_packet.py`.",
        "",
        "## Purpose",
        "",
        "Use this runbook after authors reply to the declaration confirmation email or WeChat message. Do not mark any item as confirmed without written evidence.",
        "",
        "## Evidence Folder",
        "",
        "`metadata/author_reply_evidence/`",
        "",
        "## Intake Steps",
        "",
        "1. Save each author reply as a `.txt`, `.eml`, screenshot, or exported message under `metadata/author_reply_evidence/`.",
        "2. Name evidence files by item and author, for example `funding_statement_confirmation_yi_miao.txt`.",
        "3. Update `metadata/author_metadata.tsv` only for items explicitly confirmed or corrected by authors.",
        "4. Update `metadata/credit_roles.tsv` only after role approval or correction.",
        "5. For Figure 4 acknowledgement, run `python scripts/record_corresponding_author_signoff.py` after saving the evidence.",
        "6. Re-run `python scripts/build_author_declaration_confirmation_packet.py`.",
        "7. Re-run `python scripts/build_v0_1_1_release_preflight.py` and `python scripts/build_high_impact_submission_dashboard.py`.",
        "",
        "## Confirmation Items",
        "",
        "| Item | Evidence to save | Gate unblocked | Stop condition |",
        "| --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row.get('item_id', '')} | `{row.get('evidence_to_save', '')}` | {row.get('gate_unblocked', '')} | {row.get('stop_condition', '').replace('|', '/')} |"
        )
    lines.extend(
        [
            "",
            "## Stop Rules",
            "",
            "- Stop if any author changes the author order, affiliation, ORCID, funding, or competing-interest statement.",
            "- Stop if Figure 4 is requested to become a mechanism, clinical, prognosis, therapy-response, or patient-level claim.",
            "- Stop if any private clinical data or identifiable metadata are introduced.",
            "- Stop if the official journal system requests information not represented in the local packet.",
        ]
    )
    return "\n".join(lines)


def build_eml(rows: list[dict[str, str]]) -> None:
    OUT_EMAIL_DIR.mkdir(parents=True, exist_ok=True)
    message = EmailMessage()
    message["To"] = ", ".join(f"{author['name']} <{author['email']}>" for author in AUTHORS)
    message["Subject"] = "RMTGuard author declarations and Figure 4 wording confirmation before release/presubmission"
    message["Date"] = formatdate(localtime=True)
    message.set_content(build_email_body(rows))

    if PACKET_DOCX.exists():
        message.add_attachment(
            PACKET_DOCX.read_bytes(),
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=PACKET_DOCX.name,
        )

    tmp = OUT_EML.with_suffix(".eml.tmp")
    tmp.write_bytes(bytes(message))
    tmp.replace(OUT_EML)


def build_readme() -> str:
    return """# RMTGuard Email Draft Outputs

This folder contains local `.eml` drafts. These files are not sent by scripts.

## Files

- `RMTGuard_author_declaration_confirmation_email.eml`: request final author
  confirmation for title-page metadata, CRediT, funding, competing interests,
  public-data ethics, reporting summary, and bounded Figure 4 wording.
- `RMTGuard_corresponding_author_signoff_email.eml`: narrower Figure 4
  bounded-wording acknowledgement email for Yi Miao and Han Yan.
- `RMTGuard_nature_methods_presubmission_inquiry_HOLD.eml`: locked Nature
  Methods presubmission draft. Do not send while the send packet reports a
  `hold_*` status.

## Boundary

The author-declaration and corresponding-author sign-off emails can be used
only to request author acknowledgement. The Nature Methods HOLD draft
intentionally has no recipient because the official route must be verified
manually immediately before sending.

## Regenerate

```bash
python scripts/build_author_declaration_email_packet.py
python scripts/build_corresponding_author_email_packet.py
python scripts/build_nature_methods_presubmission_send_packet.py
```
"""


def main() -> int:
    rows = read_tsv(CHECKLIST)
    write_text(OUT_EMAIL_MD, build_email_markdown(rows))
    write_text(OUT_WECHAT_MD, build_wechat_text(rows))
    write_text(OUT_INTAKE, build_intake_runbook(rows))
    build_eml(rows)
    write_text(OUT_README, build_readme())
    print(_rel(OUT_EMAIL_MD))
    print(_rel(OUT_WECHAT_MD))
    print(_rel(OUT_INTAKE))
    print(_rel(OUT_EML))
    print(_rel(OUT_README))
    print("manual_send_required")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
