from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_MANIFEST = ROOT / "results" / "release" / "release_artifact_manifest.tsv"
OUT_DIR = ROOT / "results" / "release"
STAGING_MANIFEST = OUT_DIR / "github_staging_manifest.tsv"
STAGING_SUMMARY = OUT_DIR / "github_staging_summary.tsv"
STAGING_DOC = ROOT / "docs" / "github_staging_plan.md"


def _rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.resolve())).replace("\\", "/")
    except ValueError:
        return str(path)


def _read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def _write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)
    tmp.replace(path)


def _stage_action(row: dict[str, str]) -> tuple[str, str]:
    destination = row["release_destination"]
    ignored = row["git_ignored"] == "True"
    path = row["path"]

    if destination == "github_repository" and not ignored:
        return "stage_for_initial_commit", "Commit this source, metadata, workflow, doc, or placeholder file to GitHub."
    if destination == "github_repository" and ignored:
        return "fix_ignore_before_commit", "This file is intended for GitHub but is ignored by .gitignore."
    if destination != "github_repository" and ignored:
        return "do_not_stage", "Keep out of GitHub; use accession download, scripted regeneration, or DOI-backed release assets."
    if destination != "github_repository" and not ignored:
        return "fix_ignore_or_review", "This non-GitHub artifact is not ignored and could be accidentally committed."
    return "review", f"Unhandled release destination for {path}."


def build_staging_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for row in rows:
        action, reason = _stage_action(row)
        out.append(
            {
                "action": action,
                "path": row["path"],
                "artifact_type": row["artifact_type"],
                "release_destination": row["release_destination"],
                "git_ignored": row["git_ignored"],
                "size_bytes": row["size_bytes"],
                "reason": reason,
            }
        )
    return out


def build_summary(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    summary: dict[str, dict[str, int]] = {}
    for row in rows:
        bucket = summary.setdefault(row["action"], {"file_count": 0, "size_bytes": 0})
        bucket["file_count"] += 1
        bucket["size_bytes"] += int(row["size_bytes"])
    return [
        {"action": action, "file_count": str(values["file_count"]), "size_bytes": str(values["size_bytes"])}
        for action, values in sorted(summary.items())
    ]


def write_doc(rows: list[dict[str, str]], summary: list[dict[str, str]]) -> None:
    staged = [row for row in rows if row["action"] == "stage_for_initial_commit"]
    problems = [row for row in rows if row["action"] in {"fix_ignore_before_commit", "fix_ignore_or_review", "review"}]
    archived = [row for row in rows if row["action"] == "do_not_stage"]

    lines = [
        "# GitHub Staging Plan",
        "",
        "This file is generated by `python scripts/build_github_staging_plan.py`.",
        "It is a release-safety guide only; it does not stage or commit files.",
        "",
        "Dry-run the approved staging set with:",
        "",
        "```bash",
        "python scripts/stage_github_release_files.py",
        "```",
        "",
        "Only after reviewing this file, stage the approved set with:",
        "",
        "```bash",
        "python scripts/stage_github_release_files.py --execute",
        "```",
        "",
        "## Summary",
        "",
        "| action | file_count | size_bytes |",
        "|---|---:|---:|",
    ]
    for row in summary:
        lines.append(f"| {row['action']} | {row['file_count']} | {row['size_bytes']} |")

    lines.extend(
        [
            "",
            "## Stage For Initial Commit",
            "",
            "These files are intended for the public GitHub repository.",
            "",
            "```text",
        ]
    )
    lines.extend(row["path"] for row in staged)
    lines.extend(["```", ""])

    lines.extend(
        [
            "## Do Not Stage",
            "",
            "These files are public-data downloads, processed matrices, generated results, draft figures, or local probe outputs.",
            "They should be regenerated from scripts or archived as release/Zenodo assets when needed.",
            "",
            "```text",
        ]
    )
    lines.extend(row["path"] for row in archived)
    lines.extend(["```", ""])

    lines.extend(["## Problems To Fix", ""])
    if problems:
        lines.extend(f"- `{row['path']}`: {row['action']} - {row['reason']}" for row in problems)
    else:
        lines.append("- none")
    lines.append("")

    tmp = STAGING_DOC.with_suffix(STAGING_DOC.suffix + ".tmp")
    tmp.write_text("\n".join(lines), encoding="utf-8")
    tmp.replace(STAGING_DOC)


def main() -> int:
    if not ARTIFACT_MANIFEST.exists():
        raise FileNotFoundError("Run python scripts/build_release_artifact_manifest.py first.")
    artifact_rows = _read_tsv(ARTIFACT_MANIFEST)
    staging_rows = build_staging_rows(artifact_rows)
    summary_rows = build_summary(staging_rows)
    _write_tsv(
        STAGING_MANIFEST,
        staging_rows,
        ["action", "path", "artifact_type", "release_destination", "git_ignored", "size_bytes", "reason"],
    )
    _write_tsv(STAGING_SUMMARY, summary_rows, ["action", "file_count", "size_bytes"])
    write_doc(staging_rows, summary_rows)
    print(_rel(STAGING_MANIFEST))
    print(_rel(STAGING_SUMMARY))
    print(_rel(STAGING_DOC))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
